version: "3.8"

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
      DATABASE_URL: "postgresql://symfony:symfony@postgres:5432/symfony?serverVersion=15&charset=utf8"
    volumes:
#      - /var/www/vendor/
      - ./../:/var/www/
    networks:
      - symfony-net
    depends_on:
      - postgres
      - redis

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    networks:
      - symfony-net
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm

  postgres:
    container_name: postgres
    build:
      context: ./postgres
    ports:
      - ${POSTGRES_PORT}:5432
    expose:
      - ${POSTGRES_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - symfony-net
    volumes:
      - db_data:/var/lib/postgresql/data:rw

  redis:
    container_name: redis
    build:
      context: ./redis
    ports:
      - ${REDIS_PORT}:6379
    restart: always
    networks:
      - symfony-net

volumes:
  db_data:
    driver: local

networks:
  symfony-net:
    driver: bridge